global:
  pirTest: true
jitter:
  button: 2
  presence: 5
  presence_delay: 5
instances:
  1:
    pinout:
      button: 2
      pir: 15
      green: 19
      blue: 26
    audio:
      - heads
  2:
  3:
    pinout:
      pir: 15
      green: 19
      blue: 26
    video:
      - entropy.mov
    audio:
      - heads
  4:
    pinout:
      blue: 26
      presence: 5
      green: 19
    audio:
      - tate
      # - heads
    video:
      - tate
  5:
    pinout:
      pir: 15
      green: 19
      blue: 26
    audio:
      - heads
    video:
      - heads
