global:
  pirTest: true
jitter:
  button: 2
  presence: 5
  presence_delay: 5
instances:
  1:
    audio:
      pinout:
        button: 2
        pir: 15
        green: 19
        blue: 26
  2:
  3:
    audio:
      pinout:
        pir: 15
        green: 19
        blue: 26
    video:
      pinout:
        green: 19
        blue: 26
      files:
        - entropy.mov
  4:
    video:
#      pinout:
#        blue: 26
#        distance:
#        green: 19
      folders:
        - tate
  5:
    video:
      pinout:
        pir: 15
        green: 19
        blue: 26
